# Generated by Django 2.1.5 on 2021-07-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='Address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
