# Generated by Django 2.1.5 on 2021-07-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_articles_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='Contact_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
