version: '3.7'


services:
    web:
        build: .
        command: python /code/manage.py runserver 0.0.0.0:8000
        environment: 
            - SECRET_KEY=django-insecure-t2p61_j-xk=e%owu-wo%q-&zh+u1p=(duzwxwkwwp%4!n(4pva
            - DEBUG=1
        volumes:
            - .:/code 
        ports:
            - 8000:8000
        depends_on:
            - db 
    db:
        image: postgres:11    
        environment:
            - POSTGRES_PASSWORD=postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data/  
volumes: 
    postgres_data:  